/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author CarlosSerrano BackEnd & CrisPacheco FrontEnd
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    Proceso[] pro = new Proceso[5];
    int c=0;
    DefaultListModel<String> modelo = new DefaultListModel<>();
    int Memoria=24;
    Celdas cl = new Celdas();
    int index;
    
    public Main() {
        initComponents();
        Actualizar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnCrear = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMemoria = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstProcesos = new javax.swing.JList<>();
        btnR2 = new javax.swing.JButton();
        btnR4 = new javax.swing.JButton();
        btnR1 = new javax.swing.JButton();
        btnR5 = new javax.swing.JButton();
        btnR3 = new javax.swing.JButton();
        btnR11 = new javax.swing.JButton();
        btnR9 = new javax.swing.JButton();
        btnR8 = new javax.swing.JButton();
        btnR7 = new javax.swing.JButton();
        btnR6 = new javax.swing.JButton();
        btnR12 = new javax.swing.JButton();
        btnR10 = new javax.swing.JButton();
        btnR24 = new javax.swing.JButton();
        btnR23 = new javax.swing.JButton();
        btnR22 = new javax.swing.JButton();
        btnR21 = new javax.swing.JButton();
        btnR20 = new javax.swing.JButton();
        btnR19 = new javax.swing.JButton();
        btnR18 = new javax.swing.JButton();
        btnR17 = new javax.swing.JButton();
        btnR16 = new javax.swing.JButton();
        btnR15 = new javax.swing.JButton();
        btnR14 = new javax.swing.JButton();
        btnR13 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblMemoria = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador de Memoria");
        setIconImage(new ImageIcon(getClass().getResource("/Img/icon.png")).getImage());
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 103, 768, 12);

        jPanel1.setBackground(new java.awt.Color(0,0,0,129));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Creador de Procesos");

        btnCrear.setBackground(new java.awt.Color(0,0,0,129));
        btnCrear.setForeground(java.awt.Color.white);
        btnCrear.setLabel("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Nombre");

        txtNombre.setBackground(new java.awt.Color(0,0,0,80));
        txtNombre.setForeground(java.awt.Color.white);
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setName(""); // NOI18N

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Tamaño de Memoria");

        txtMemoria.setBackground(new java.awt.Color(0,0,0,80));
        txtMemoria.setForeground(java.awt.Color.white);
        txtMemoria.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(120, 120, 120))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btnCrear))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(btnCrear)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 126, 286, 310);

        jPanel2.setBackground(new java.awt.Color(0,0,0,129));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Lista de Procesos");

        lstProcesos.setBackground(java.awt.Color.gray);
        lstProcesos.setForeground(java.awt.Color.white);
        lstProcesos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstProcesos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstProcesosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstProcesos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(590, 130, 160, 312);

        btnR2.setBackground(java.awt.Color.lightGray);
        btnR2.setFocusPainted(false);
        btnR2.setFocusable(false);
        btnR2.setRolloverEnabled(false);
        getContentPane().add(btnR2);
        btnR2.setBounds(50, 10, 30, 80);

        btnR4.setBackground(java.awt.Color.lightGray);
        btnR4.setFocusPainted(false);
        btnR4.setFocusable(false);
        btnR4.setRolloverEnabled(false);
        getContentPane().add(btnR4);
        btnR4.setBounds(110, 10, 30, 80);

        btnR1.setBackground(java.awt.Color.lightGray);
        btnR1.setFocusPainted(false);
        btnR1.setFocusable(false);
        btnR1.setRolloverEnabled(false);
        getContentPane().add(btnR1);
        btnR1.setBounds(20, 10, 30, 80);

        btnR5.setBackground(java.awt.Color.lightGray);
        btnR5.setFocusPainted(false);
        btnR5.setFocusable(false);
        btnR5.setRolloverEnabled(false);
        getContentPane().add(btnR5);
        btnR5.setBounds(140, 10, 30, 80);

        btnR3.setBackground(java.awt.Color.lightGray);
        btnR3.setFocusPainted(false);
        btnR3.setFocusable(false);
        btnR3.setRolloverEnabled(false);
        getContentPane().add(btnR3);
        btnR3.setBounds(80, 10, 30, 80);

        btnR11.setBackground(java.awt.Color.lightGray);
        btnR11.setFocusPainted(false);
        btnR11.setFocusable(false);
        btnR11.setRolloverEnabled(false);
        getContentPane().add(btnR11);
        btnR11.setBounds(320, 10, 30, 80);

        btnR9.setBackground(java.awt.Color.lightGray);
        btnR9.setFocusPainted(false);
        btnR9.setFocusable(false);
        btnR9.setRolloverEnabled(false);
        getContentPane().add(btnR9);
        btnR9.setBounds(260, 10, 30, 80);

        btnR8.setBackground(java.awt.Color.lightGray);
        btnR8.setFocusPainted(false);
        btnR8.setFocusable(false);
        btnR8.setRolloverEnabled(false);
        getContentPane().add(btnR8);
        btnR8.setBounds(230, 10, 30, 80);

        btnR7.setBackground(java.awt.Color.lightGray);
        btnR7.setFocusPainted(false);
        btnR7.setFocusable(false);
        btnR7.setRolloverEnabled(false);
        getContentPane().add(btnR7);
        btnR7.setBounds(200, 10, 30, 80);

        btnR6.setBackground(java.awt.Color.lightGray);
        btnR6.setFocusPainted(false);
        btnR6.setFocusable(false);
        btnR6.setRolloverEnabled(false);
        getContentPane().add(btnR6);
        btnR6.setBounds(170, 10, 30, 80);

        btnR12.setBackground(java.awt.Color.lightGray);
        btnR12.setFocusPainted(false);
        btnR12.setFocusable(false);
        btnR12.setRolloverEnabled(false);
        getContentPane().add(btnR12);
        btnR12.setBounds(350, 10, 30, 80);

        btnR10.setBackground(java.awt.Color.lightGray);
        btnR10.setFocusPainted(false);
        btnR10.setFocusable(false);
        btnR10.setRolloverEnabled(false);
        getContentPane().add(btnR10);
        btnR10.setBounds(290, 10, 30, 80);

        btnR24.setBackground(java.awt.Color.lightGray);
        btnR24.setFocusPainted(false);
        btnR24.setFocusable(false);
        btnR24.setRolloverEnabled(false);
        getContentPane().add(btnR24);
        btnR24.setBounds(710, 10, 30, 80);

        btnR23.setBackground(java.awt.Color.lightGray);
        btnR23.setFocusPainted(false);
        btnR23.setFocusable(false);
        btnR23.setRolloverEnabled(false);
        getContentPane().add(btnR23);
        btnR23.setBounds(680, 10, 30, 80);

        btnR22.setBackground(java.awt.Color.lightGray);
        btnR22.setFocusPainted(false);
        btnR22.setFocusable(false);
        btnR22.setRolloverEnabled(false);
        getContentPane().add(btnR22);
        btnR22.setBounds(650, 10, 30, 80);

        btnR21.setBackground(java.awt.Color.lightGray);
        btnR21.setFocusPainted(false);
        btnR21.setFocusable(false);
        btnR21.setRolloverEnabled(false);
        getContentPane().add(btnR21);
        btnR21.setBounds(620, 10, 30, 80);

        btnR20.setBackground(java.awt.Color.lightGray);
        btnR20.setFocusPainted(false);
        btnR20.setFocusable(false);
        btnR20.setRolloverEnabled(false);
        getContentPane().add(btnR20);
        btnR20.setBounds(590, 10, 30, 80);

        btnR19.setBackground(java.awt.Color.lightGray);
        btnR19.setFocusPainted(false);
        btnR19.setFocusable(false);
        btnR19.setRolloverEnabled(false);
        getContentPane().add(btnR19);
        btnR19.setBounds(560, 10, 30, 80);

        btnR18.setBackground(java.awt.Color.lightGray);
        btnR18.setFocusPainted(false);
        btnR18.setFocusable(false);
        btnR18.setRolloverEnabled(false);
        getContentPane().add(btnR18);
        btnR18.setBounds(530, 10, 30, 80);

        btnR17.setBackground(java.awt.Color.lightGray);
        btnR17.setFocusPainted(false);
        btnR17.setFocusable(false);
        btnR17.setRolloverEnabled(false);
        getContentPane().add(btnR17);
        btnR17.setBounds(500, 10, 30, 80);

        btnR16.setBackground(java.awt.Color.lightGray);
        btnR16.setFocusPainted(false);
        btnR16.setFocusable(false);
        btnR16.setRolloverEnabled(false);
        getContentPane().add(btnR16);
        btnR16.setBounds(470, 10, 30, 80);

        btnR15.setBackground(java.awt.Color.lightGray);
        btnR15.setFocusPainted(false);
        btnR15.setFocusable(false);
        btnR15.setRolloverEnabled(false);
        getContentPane().add(btnR15);
        btnR15.setBounds(440, 10, 30, 80);

        btnR14.setBackground(java.awt.Color.lightGray);
        btnR14.setFocusPainted(false);
        btnR14.setFocusable(false);
        btnR14.setRolloverEnabled(false);
        getContentPane().add(btnR14);
        btnR14.setBounds(410, 10, 30, 80);

        btnR13.setBackground(java.awt.Color.lightGray);
        btnR13.setFocusPainted(false);
        btnR13.setFocusable(false);
        btnR13.setRolloverEnabled(false);
        getContentPane().add(btnR13);
        btnR13.setBounds(380, 10, 30, 80);

        jButton1.setBackground(java.awt.Color.magenta);
        jButton1.setForeground(java.awt.Color.white);
        jButton1.setText("Pasando de Espera a Usado");
        jButton1.setFocusable(false);
        jButton1.setRolloverEnabled(false);
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 420, 220, 30);

        jButton2.setBackground(java.awt.Color.blue);
        jButton2.setForeground(java.awt.Color.white);
        jButton2.setText("Libre");
        jButton2.setFocusable(false);
        jButton2.setRolloverEnabled(false);
        getContentPane().add(jButton2);
        jButton2.setBounds(450, 390, 80, 30);

        jButton3.setBackground(java.awt.Color.green);
        jButton3.setForeground(java.awt.Color.white);
        jButton3.setText("Usado");
        jButton3.setFocusPainted(false);
        jButton3.setRolloverEnabled(false);
        getContentPane().add(jButton3);
        jButton3.setBounds(310, 390, 80, 30);

        lblMemoria.setBackground(java.awt.Color.black);
        lblMemoria.setForeground(java.awt.Color.white);
        lblMemoria.setText("Memoria");
        getContentPane().add(lblMemoria);
        lblMemoria.setBounds(590, 440, 50, 14);

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(660, 440, 90, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/backfont.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 780, 470);

        setBounds(0, 0, 784, 498);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        pro[c] = new Proceso(c, "Listo", txtNombre.getText(), Integer.parseInt(txtMemoria.getText()));
        modelo.addElement(pro[c].getNombre());
        lstProcesos.setModel(modelo);
        Memoria -= Integer.parseInt(txtMemoria.getText());
        lblMemoria.setText(Integer.toString(Memoria));
        cl.Agregar(pro[c].Memoria);
        Actualizar();
        c++;
        txtNombre.setText("");
        txtMemoria.setText("");
        
    }//GEN-LAST:event_btnCrearActionPerformed

    private void lstProcesosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstProcesosMouseClicked
        index = lstProcesos.getSelectedIndex();
        lblMemoria.setText(pro[index].getEstado());
    }//GEN-LAST:event_lstProcesosMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        cl.Eliminar(pro[index].getMemoria());
        Actualizar();
        modelo.remove(index);
        lstProcesos.setModel(modelo);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Actualizar(){
        btnR1.setBackground(cl.ColorCell(1));
        btnR2.setBackground(cl.ColorCell(2));
        btnR3.setBackground(cl.ColorCell(3));
        btnR4.setBackground(cl.ColorCell(4));
        btnR5.setBackground(cl.ColorCell(5));
        btnR6.setBackground(cl.ColorCell(6));
        btnR7.setBackground(cl.ColorCell(7));
        btnR8.setBackground(cl.ColorCell(8));
        btnR9.setBackground(cl.ColorCell(9));
        btnR10.setBackground(cl.ColorCell(10));
        btnR11.setBackground(cl.ColorCell(11));
        btnR12.setBackground(cl.ColorCell(12));
        btnR13.setBackground(cl.ColorCell(13));
        btnR14.setBackground(cl.ColorCell(14));
        btnR15.setBackground(cl.ColorCell(15));
        btnR16.setBackground(cl.ColorCell(16));
        btnR17.setBackground(cl.ColorCell(17));
        btnR18.setBackground(cl.ColorCell(18));
        btnR19.setBackground(cl.ColorCell(19));
        btnR20.setBackground(cl.ColorCell(20));
        btnR21.setBackground(cl.ColorCell(21));
        btnR22.setBackground(cl.ColorCell(22));
        btnR23.setBackground(cl.ColorCell(23));
        btnR24.setBackground(cl.ColorCell(24));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    public javax.swing.JButton btnR1;
    public javax.swing.JButton btnR10;
    public javax.swing.JButton btnR11;
    public javax.swing.JButton btnR12;
    public javax.swing.JButton btnR13;
    public javax.swing.JButton btnR14;
    public javax.swing.JButton btnR15;
    public javax.swing.JButton btnR16;
    public javax.swing.JButton btnR17;
    public javax.swing.JButton btnR18;
    public javax.swing.JButton btnR19;
    public javax.swing.JButton btnR2;
    public javax.swing.JButton btnR20;
    public javax.swing.JButton btnR21;
    public javax.swing.JButton btnR22;
    public javax.swing.JButton btnR23;
    public javax.swing.JButton btnR24;
    public javax.swing.JButton btnR3;
    public javax.swing.JButton btnR4;
    public javax.swing.JButton btnR5;
    public javax.swing.JButton btnR6;
    public javax.swing.JButton btnR7;
    public javax.swing.JButton btnR8;
    public javax.swing.JButton btnR9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblMemoria;
    private javax.swing.JList<String> lstProcesos;
    private javax.swing.JTextField txtMemoria;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
